meta_product_name: "Fitsme"
meta_title: "FitsMe - seamless sizing. changing the way customers shop"
meta_description: "Fitsme is a sizing recommendation tool for your e-commerce store. Reduce returns and increase conversions"
meta_image: "cover.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
